# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ont.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ont.proto',
  package='ont',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tont.proto\x12\x03ont\"\x1b\n\x0bRequestData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"B\n\x0cResponseData\x12\x13\n\x0breturn_code\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\xea\x01\n\nONTService\x12\x34\n\x0b\x43reateONTID\x12\x10.ont.RequestData\x1a\x11.ont.ResponseData\"\x00\x12\x34\n\x0b\x44\x65leteONTID\x12\x10.ont.RequestData\x1a\x11.ont.ResponseData\"\x00\x12\x36\n\rTransferONTID\x12\x10.ont.RequestData\x1a\x11.ont.ResponseData\"\x00\x12\x38\n\x0fGetCreateNotify\x12\x10.ont.RequestData\x1a\x11.ont.ResponseData\"\x00\x62\x06proto3')
)




_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='ont.RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ont.RequestData.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=45,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='ResponseData',
  full_name='ont.ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_code', full_name='ont.ResponseData.return_code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ont.ResponseData.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ont.ResponseData.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTDATA,
  __module__ = 'ont_pb2'
  # @@protoc_insertion_point(class_scope:ont.RequestData)
  ))
_sym_db.RegisterMessage(RequestData)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEDATA,
  __module__ = 'ont_pb2'
  # @@protoc_insertion_point(class_scope:ont.ResponseData)
  ))
_sym_db.RegisterMessage(ResponseData)



_ONTSERVICE = _descriptor.ServiceDescriptor(
  name='ONTService',
  full_name='ont.ONTService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=350,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateONTID',
    full_name='ont.ONTService.CreateONTID',
    index=0,
    containing_service=None,
    input_type=_REQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteONTID',
    full_name='ont.ONTService.DeleteONTID',
    index=1,
    containing_service=None,
    input_type=_REQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TransferONTID',
    full_name='ont.ONTService.TransferONTID',
    index=2,
    containing_service=None,
    input_type=_REQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCreateNotify',
    full_name='ont.ONTService.GetCreateNotify',
    index=3,
    containing_service=None,
    input_type=_REQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONTSERVICE)

DESCRIPTOR.services_by_name['ONTService'] = _ONTSERVICE

# @@protoc_insertion_point(module_scope)
